<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <DisableBuildCompression>true</DisableBuildCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**/._*" />
    <Content Remove="**/._*" />
    <EmbeddedResource Remove="**/._*" />
    <None Remove="**/._*" />
  </ItemGroup>

</Project>
